name: cellpose_cpu
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - numpy>=1.20
  - numba>=0.43.1
  - scipy
  - scikit-image
  - opencv
  - pyqt
  - pyqtgraph>=0.11.0rc0
  - natsort
  - tqdm
  - tifffile
  - fastremap
  - cellpose==1.0.2
  - matplotlib

  # CPU-only PyTorch (no CUDA)
  - pytorch=1.10.2
  - torchvision
  - torchaudio
